name: CI

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  archive:
    name: Archive
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install cross binutils
      run: |
        sudo apt update
        sudo apt install -y binutils-aarch64-linux-gnu

    - name: Build fnalibs
      run: ./build-fnalibs.sh
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Archive fnalibs
      uses: actions/upload-artifact@v4
      with:
        name: fnalibs
        path: fnalibs/

  archive-apple:
    name: Archive (Apple)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build fnalibs-apple
      run: ./build-fnalibs-apple.sh
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Archive fnalibs-apple
      uses: actions/upload-artifact@v4
      with:
        name: fnalibs-apple
        path: fnalibs-apple/

  archive-wasm:
    name: Archive (WASM)
    strategy:
      matrix:
        pthread_enabled: [true, false]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: emscripten-core/setup-emsdk@v15
      with:
        version: 3.1.56

    - name: Verify Emscripten
      run: emcc -v

    - name: Make build-fnalibs-wasm.sh executable
      run: chmod +x ./build-fnalibs-wasm.sh

    - name: Build fnalibs-wasm
      run: |
        if [ "${{ matrix.pthread_enabled }}" = "true" ]; then
          ./build-fnalibs-wasm.sh --pthread-enabled
        else
          ./build-fnalibs-wasm.sh
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Archive fnalibs-wasm
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.pthread_enabled == 'true' && 'fnalibs-wasm-mt' || 'fnalibs-wasm-st' }}
        path: ${{ matrix.pthread_enabled == 'true' && 'fnalibs-wasm-mt/' || 'fnalibs-wasm-st/' }}
